github.com:
    users:
        ryannewcomer:
            oauth_token: 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
    git_protocol: https
    user: ryannewcomer
    oauth_token: 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
