github.com:
    users:
        ryannewcomer:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: ryannewcomer
